apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: etcd-backup-bp
  namespace: kasten-io
actions:
  beforeBackup:
    phases:    
    - name: createBackupPVC
      func: KubeOps
      args:
        operation: create
        namespace: 'openshift-etcd'
        spec: |-
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: etcd-backup-pvc
            namespace: openshift-etcd
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
    - name: createEtcdBackup
      func: KubeOps
      args:
        operation: create        
        spec: |-
          apiVersion: operator.openshift.io/v1alpha1
          kind: EtcdBackup
          metadata:
            name: etcd-single-backup            
          spec:
            pvcName: etcd-backup-pvc
    - name: waitForBackup
      func: WaitV2
      args:
        timeout: 5m
        conditions:
          anyOf:
          - condition: '{{ $available := false }}{{ range $condition := $.status.conditions }}{{ if and (eq .message "Complete") (eq .status "True")  }}{{ $available = true }}{{ end }}{{ end }}{{ if $available }}true{{ else }}false{{ end }}'
            objectReference:
              apiVersion: "v1alpha1"
              group: "operator.openshift.io"
              name: "etcd-single-backup"              
              resource: "etcdbackups"
  afterBackup:
    phases:    
    # bug kubeops delete does not work on non-namespaced resources
    # reported we use a single kubetask to delete the resource in the meantime
    #- name: removeEtcdBackup
    #  func: KubeOps
    #  args:
    #    operation: delete
    #    objectReference:
    #      apiVersion: "v1alpha1"
    #      group: "operator.openshift.io"
    #      resource: "etcdbackups"
    #      name: "etcd-single-backup"          
    - name: removeEtcdBackup
      func: KubeTask      
      args:
        image: ghcr.io/kanisterio/kanister-kubectl-1.18:0.113.0
        command:
          - sh
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            kubectl delete etcdbackups.operator.openshift.io etcd-single-backup    
            # kubectl delete pvc etcd-backup-pvc -n openshift-etcd        
    - name: removePVC 
      func: KubeOps
      args:
        operation: delete
        objectReference:
          apiVersion: "v1"
          resource: "persistentvolumeclaims"
          name: "etcd-backup-pvc"
          namespace: 'openshift-etcd'